name: o_elefante
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.13
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.16
  firebase_analytics: ^5.0.2
  path_provider: ^2.0.9
  shared_preferences: ^2.0.13
  local_auth: ^2.0.0
  scoped_model: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/logo.jpg